### ISSUE TITLE
Load .slack from homedir.

### ISSUE THREAD

**Issue by burtonator** [rockymadden/slack-cli#52]
Would be nice to have a .slack file in my home dir.

On our production boxes we could then have slack automatically configured easily by automation and easily send messages.

We could use .bashrc but that's kind of hacky IMO

**Comment by burtonator** [comment]
```bash

if [ -f "${HOME}/.slack" ]; then
  token=$(sed -n '1p' < "${etcdir}/.slack")
fi

```

.. would do it. That would be the default then you could slack init or set an env to override it.

**Comment by rockymadden** [comment]
This should be possible via `make install` as shown here: https://github.com/rockymadden/slack-cli#via-make: https://github.com/rockymadden/slack-cli#via-make

You would set the `etcdir` to your home directory. Please let me know if this doesn't work and we can reopen.
