### ISSUE TITLE
Don't put .slack in 'etcdir'

### ISSUE THREAD

**Issue by burtonator** [rockymadden/slack-cli#53]
I just looked at the source you're putting the configuration file in the installation dir of the script.

Is this a bug?

My .slack shouldn't be in /usr/bin... 

if anything it should be in /etc/ for system wide installs.

**Comment by rockymadden** [comment]
This is a convention/requirement of [homebrew](https://brew.sh). What you describe is possible if you install manually and make arguments to `make`: https://github.com/rockymadden/slack-cli#via-make
