### ISSUE TITLE
Status update cannot include spaces

### ISSUE THREAD

**Issue by whoward** [rockymadden/slack-cli#59]
I was just trying to script together a simple status updater for pomodoros and noticed what appears to be a bug in the argument parsing:

```bash
slack status edit --text "Pomodoro until DATE" --emoji :tomato:
```

Under the hood it appears to run this invalid CURL command 

```bash
curl -s -X POST https://slack.com/api/users.profile.set --data-urlencode 'profile={"status_text":"Pomodoro' until 'DATE", "status_emoji":":tomato:"}' --data-urlencode token=<redacted>
```

and you get back this from the Slack API:

```json
{
  "ok": false,
  "error": "invalid_profile"
}
```

**Comment by gabecase** [comment]
ran into this issue as well

**Comment by rockymadden** [comment]
Thanks for the report, I can also reproduce this.

**Comment by rockymadden** [comment]
Fix with https://github.com/rockymadden/slack-cli/pull/70. Thanks again for the report!
