### ISSUE TITLE
Status clear command

### ISSUE THREAD

**Issue by whoward** [rockymadden/slack-cli#60]
There seems to be no easy way to script clearing your status from the command line without requiring some user interaction

The following command goes into interactive mode
```bash
slack status edit --text '' --emoji ''
```

The best workaround I have so far is pretty unintuitive and brittle:
```bash
printf "\n\n" | slack status edit
```

**Comment by rockymadden** [comment]
Thanks for the report. Yeah, some of this is to do with my `-z` and `-n` checks with bash. Perhaps a dedicated `slack status clear` command is in order?

**Comment by whoward** [comment]
yup that would do the job for sure!

**Comment by rockymadden** [comment]
All set via #71. Coming at ya in `0.17.0` in just a moment.
