### ISSUE TITLE
status clearing

### ISSUE THREAD

**Issue by chrisamow** [rockymadden/slack-cli#91]
within the native client to clear status you can just "/status "

i've tried a bunch of variations with the cli but it seems i need to set a specific emoji?

also, i was trying to use the cli to delete messages but am not sure how to get the timestamp (since it includes finer detail info than what is displayed on the client)

thanks Rocky!

**Comment by c-amow** [comment]
aah, i just saw "status clear" so nevermind!

although any insight into how to get timestamps would be appreciated...
(maybe message list support?)
